[env]
PHOENIX_PREFIX = { value = "/tmp/phoenix", condition.env_not_set = [
  "PHOENIX_PREFIX",
] }
PROJECT_ROOT = { script = ["pwd"] }
TARGET_DIR = "${PROJECT_ROOT}/target"
PHOENIX_TARGET_DIR = "${PROJECT_ROOT}/target/phoenix"
COMMON_DEPS_DIR = "${PHOENIX_TARGET_DIR}/common_deps"
PHOENIX_COMMON_DEPS_DIR = "${COMMON_DEPS_DIR}"
PHOENIX_RUSTC_WRAPPER = "${TARGET_DIR}/release/rustc_wrapper"
# This is a hack to force enabling std feature for indexmap
CARGO_FEATURE_STD="1"

[tasks.default]
alias = "dev-test-flow"

# the default make target
[tasks.dev-test-flow]
description = '''
Development testing flow.
You can customize your own development testing flow.
It current builds phoenixos; builds and deploys phoenix plugins, and runs phoenix daemon.
'''
dependencies = [
  "build-phoenixos",
  "build-plugins",
  "deploy-plugins",
  "build-capi",
  "run-phoenixos",
]

[tasks.phoenix_cargo]
description = "Build phoenix_cargo tool."
cwd = "${PROJECT_ROOT}"
script = "cargo build --release --bin phoenix_cargo --bin rustc_wrapper"

[tasks.phoenix_common]
description = '''
Build phoenix-common package and deploy it to target/host_dep.
'''
cwd = "${PROJECT_ROOT}"
script = '''
#!/usr/bin/env bash
set -euo pipefail
mkdir -p ${PHOENIX_TARGET_DIR}
mkdir -p ${COMMON_DEPS_DIR}
# ${TARGET_DIR}/release/phoenix_cargo \
#   --build-common-deps \
#   --common-deps ${COMMON_DEPS_DIR} -- \
#   build --release --target-dir ${PHOENIX_TARGET_DIR} -p phoenix_common

RUSTC_WRAPPER=${PHOENIX_RUSTC_WRAPPER} \
PHOENIX_IS_COMMON_DEP=1 \
cargo build --release --target-dir ${PHOENIX_TARGET_DIR} -p phoenix_common
'''
dependencies = ["phoenix_cargo"]

[tasks.build-phoenixos]
description = "Build phoenixos."
cwd = "${PROJECT_ROOT}"
script = '''
mkdir -p ${PHOENIX_TARGET_DIR}
# ${TARGET_DIR}/release/phoenix_cargo \
#   --common-deps ${COMMON_DEPS_DIR} -- \
#   build --release --target-dir ${PHOENIX_TARGET_DIR} -p phoenixos

RUSTC_WRAPPER=${PHOENIX_RUSTC_WRAPPER} \
cargo build --release --target-dir ${PHOENIX_TARGET_DIR} -p phoenixos
'''
dependencies = ["phoenix_common"]

[tasks.phoenixos]
alias = "build-phoenixos"

[tasks.run-phoenixos]
description = "Start the phoenixos system service."
cwd = "${PROJECT_ROOT}"
command = "${PHOENIX_TARGET_DIR}/release/phoenixos"
args = ["${@}"]

[tasks.run]
alias = "run-phoenixos"

[tasks.build-capi]
description = "Generate C headers and libraries for phoenix provider in rdma-core"
cwd = "${PROJECT_ROOT}"
script = "cargo cinstall --release -p phoenix-syscalls --prefix=${PHOENIX_PREFIX}"

[tasks.build-plugins]
description = '''
Build specified plugins by package name.
If no argument is provided, build all plugins in this workspace.
'''
# cargo make build-plugins [package-name]*
cwd = "${PROJECT_ROOT}"
script = '''
default_plugins=`cargo metadata --format-version 1 | jq -r '
  .packages[].manifest_path
  | select(test("src/plugin"))
  | sub("/Cargo.toml$"; "")  # Remove the /Cargo.toml part
  | split("/") | last        # Get only the last directory name
  | "-p phoenix-" + .
'`
pkgs=`test -z "$@" && echo ${default_plugins} || printf -- '-p phoenix-%s ' "$@"`
# ${TARGET_DIR}/release/phoenix_cargo \
#   --common-deps ${COMMON_DEPS_DIR} -- \
#   build --release --target-dir ${PHOENIX_TARGET_DIR} \
#   ${pkgs}

RUSTC_WRAPPER=${PHOENIX_RUSTC_WRAPPER} \
cargo build --release --target-dir ${PHOENIX_TARGET_DIR} ${pkgs}
'''

[tasks.deploy-plugins]
description = "Deploy all plugins."
script = "${PROJECT_ROOT}/scripts/deploy_plugins.sh ${PHOENIX_PREFIX} ${PHOENIX_TARGET_DIR}"

[tasks.build-phoenix-cli]
description = "Build phoenix-cli tools."
script = '''
cargo build --release -p phoenixctl
'''

[tasks.build]
description = "Forward everything to cargo build."
command = "cargo"
args = ["build", "${@}"]

[config]
default_to_workspace = false
